"""
PRD Starter Generator - Documentation Generation

DocsGenerator class - handles generation of research summaries, GDD documents,
PRD files, and initialization scripts.
"""

import sys
from datetime import datetime
from pathlib import Path

from renderer import TemplateRenderer
from model_types import ProjectConfig
from utils import resolve_tech_stack_commands


class DocsGenerator:
    """Generates project documentation files."""

    def __init__(self, project_root: Path, renderer: TemplateRenderer):
        """Initialize the documentation generator.

        Args:
            project_root: Root directory of the project
            renderer: TemplateRenderer instance for rendering templates
        """
        self.project_root = Path(project_root).resolve()
        self.templates_dir = self.project_root / ".claude" / "templates"
        self.scripts_dir = self.project_root / ".claude" / "scripts"
        self.renderer = renderer

    def generate_init_script(self, project_config: ProjectConfig, tech_stack: dict,
                            research_data: dict = None) -> bool:
        """Generate project initialization script based on tech stack.

        Uses 6-level priority chain for command resolution:
        1. User explicit override
        2. Discovered commands (high confidence)
        3. Preset commands
        4. Discovered commands (medium confidence)
        5. Hardcoded runtime table
        6. Safe fallback (Node/npm)

        Args:
            project_config: Project configuration
            tech_stack: Technology stack configuration with runtime, packageManager, etc.
            research_data: Optional research data with discoveredCommands from pm-research-specialist

        Returns:
            True if generation was successful
        """
        try:
            # Use command resolution priority chain
            resolved = resolve_tech_stack_commands(tech_stack, research_data)
            runtime = resolved["runtime"]
            commands_source = resolved["source"]

            package_manager = tech_stack.get("packageManager", resolved["package_manager"])
            init_command = tech_stack.get("initCommand", resolved["init"])
            install_command = tech_stack.get("installCommand", resolved["install"])

            # Log command source for debugging
            if commands_source.startswith("research"):
                print(f"  Using {commands_source} commands for runtime: {runtime}")

            # Replace placeholder in init command
            init_command = init_command.replace("{PROJECT_NAME}", project_config.name)

            script_content = f"""#!/bin/bash
# Auto-generated by Ralph Orchestra PRD Starter
# Project initialization script for {project_config.name}
# Command source: {commands_source}

set -e  # Exit on error

PROJECT_NAME="{project_config.name}"
RUNTIME="{runtime}"
PACKAGE_MANAGER="{package_manager}"

echo "🚀 Initializing $PROJECT_NAME..."

# 1. Check if package manager is available
if ! command -v $PACKAGE_MANAGER &> /dev/null; then
    echo "❌ Error: $PACKAGE_MANAGER not found. Please install it first."
    echo "   Visit: https://{"devguide.python.org" if runtime == "python" else "nodejs.org" if runtime == "node" else "rustup.rs" if runtime == "rust" else "go.dev" if runtime == "go" else "docs.microsoft.com" if runtime == "dotnet" else "maven.apache.org"}"
    exit 1
fi

# 2. Initialize project (if not already)
if [ ! -f "package.json" ] && [ ! -f "requirements.txt" ] && [ ! -f "Cargo.toml" ] && [ ! -f "go.mod" ] && [ ! -f "pom.xml" ] && [ ! -f "*.csproj" ]; then
    echo "📁 Initializing project structure..."
    {init_command}
else
    echo "ℹ️  Project already initialized, skipping init step."
fi

# 3. Install dependencies
echo "📦 Installing dependencies..."
{install_command}

# 4. Verify installation
echo "✅ Project initialization complete!"
echo ""
echo "Next steps:"
echo "  - Run your dev server: {tech_stack.get('devCommand', resolved.get('dev', 'npm run dev'))}"
echo "  - Start Ralph coordinator: /ralph-coordinator-event"
"""

            script_path = self.scripts_dir / "init-project.sh"
            script_path.write_text(script_content, encoding='utf-8')

            # Also create PowerShell version for Windows
            ps_script_content = f"""# Auto-generated by Ralph Orchestra PRD Starter
# Project initialization script for {project_config.name}

$ErrorActionPreference = "Stop"

$PROJECT_NAME = "{project_config.name}"
$RUNTIME = "{runtime}"
$PACKAGE_MANAGER = "{package_manager}"

Write-Host "🚀 Initializing $PROJECT_NAME..." -ForegroundColor Green

# 1. Check if package manager is available
$packageCmd = Get-Command $PACKAGE_MANAGER -ErrorAction SilentlyContinue
if (-not $packageCmd) {{
    Write-Host "❌ Error: $PACKAGE_MANAGER not found. Please install it first." -ForegroundColor Red
    Write-Host "   Visit: https://{"devguide.python.org" if runtime == "python" else "nodejs.org" if runtime == "node" else "rustup.rs" if runtime == "rust" else "go.dev" if runtime == "go" else "docs.microsoft.com" if runtime == "dotnet" else "maven.apache.org"}"
    exit 1
}}

# 2. Initialize project (if not already)
$hasProjectFile = Test-Path "package.json" -or Test-Path "requirements.txt" -or Test-Path "Cargo.toml" -or Test-Path "go.mod" -or Test-Path "pom.xml" -or (Get-ChildItem -Filter "*.csproj" -ErrorAction SilentlyContinue)
if (-not $hasProjectFile) {{
    Write-Host "📁 Initializing project structure..." -ForegroundColor Cyan
    {init_command.replace('source venv/bin/activate', '.\\venv\\Scripts\\Activate.ps1')}
}} else {{
    Write-Host "ℹ️  Project already initialized, skipping init step." -ForegroundColor Yellow
}}

# 3. Install dependencies
Write-Host "📦 Installing dependencies..." -ForegroundColor Cyan
{install_command}

# 4. Verify installation
Write-Host "✅ Project initialization complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  - Run your dev server: {tech_stack.get('devCommand', resolved.get('dev', 'npm run dev'))}"
Write-Host "  - Start Ralph coordinator: /ralph-coordinator-event"
"""

            ps_script_path = self.scripts_dir / "init-project.ps1"
            ps_script_path.write_text(ps_script_content, encoding='utf-8')

            return True
        except Exception as e:
            print(f"Error generating init script: {e}", file=sys.stderr)
            return False

    def generate_research_summary(self, research_data: dict, project_config: ProjectConfig) -> bool:
        """Generate research summary document from pm-research-specialist findings.

        Args:
            research_data: Research data collected by pm-research-specialist
            project_config: Project configuration

        Returns:
            True if generation was successful
        """
        try:
            research_file = self.project_root / "docs" / "research-summary.md"
            research_file.parent.mkdir(parents=True, exist_ok=True)

            # Format similar projects
            similar_projects = ""
            if research_data.get("similarProjects"):
                similar_projects = "\n".join([
                    f"- [{p.get('name', 'Unknown')}]({p.get('url', '#')}) - {p.get('relevance', '')}"
                    for p in research_data["similarProjects"]
                ])

            # Format best practices
            best_practices = ""
            if research_data.get("bestPractices"):
                best_practices = "\n".join([
                    f"- **{p.get('practice', '')}** - {p.get('reason', '')}"
                    for p in research_data["bestPractices"]
                ])

            # Format common pitfalls
            pitfalls = ""
            if research_data.get("commonPitfalls"):
                pitfalls = "\n".join([
                    f"- **{p.get('pitfall', '')}** - {p.get('avoidance', '')}"
                    for p in research_data["commonPitfalls"]
                ])

            # Format questions and answers
            q_and_a = ""
            if research_data.get("questionsAnswered"):
                q_and_a = "\n".join([
                    f"**Q: {qa.get('question', '')}**\nA: {qa.get('answer', '')}\n"
                    for qa in research_data["questionsAnswered"]
                ])

            # Format references
            references = ""
            if research_data.get("references"):
                references = "\n".join([
                    f"- [{r.get('title', 'Unknown')}]({r.get('url', '#')})"
                    for r in research_data["references"]
                ])

            content = f"""# Project Research Summary

**Project:** {project_config.name}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Similar Projects Found

{similar_projects if similar_projects else "No similar projects documented."}

---

## Best Practices for {project_config.tech_stack or "Selected Tech Stack"}

{best_practices if best_practices else "No best practices documented."}

---

## Common Pitfalls to Avoid

{pitfalls if pitfalls else "No pitfalls documented."}

---

## Questions and Answers

{q_and_a if q_and_a else "No questions documented."}

---

## References

{references if references else "No references documented."}

---

*This document was automatically generated from research conducted by the pm-research-specialist agent.*
"""
            research_file.write_text(content, encoding='utf-8')
            print(f"✓ Generated research summary at {research_file}")
            return True
        except Exception as e:
            print(f"Error generating research summary: {e}", file=sys.stderr)
            return False

    def generate_gdd_summary(self, gdd_data: dict, project_config: ProjectConfig) -> bool:
        """Generate GDD summary document from thermite facilitator findings.

        Handles both minimal state format and rich gdd-findings.json format gracefully.

        Args:
            gdd_data: GDD data collected by gamedesigner-thermite-facilitator
            project_config: Project configuration

        Returns:
            True if generation was successful
        """
        try:
            # Create design directory
            design_dir = self.project_root / "docs" / "design"
            design_dir.mkdir(parents=True, exist_ok=True)

            # Format design decisions (handle both minimal and rich formats)
            decisions = ""
            if gdd_data.get("designDecisions"):
                decision_parts = []
                for d in gdd_data["designDecisions"]:
                    decision_id = d.get('id', 'DEC-XXX')
                    title = d.get('title', 'Unknown')
                    status = d.get('status', 'Unknown')
                    decision = d.get('decision', '')
                    rationale = d.get('rationale', '')
                    
                    # Build decision entry
                    entry = f"### {decision_id}: {title}\n"
                    entry += f"**Status:** {status}\n"
                    
                    # Add pillars if available
                    if d.get('pillars'):
                        pillars_str = ", ".join(d['pillars']) if isinstance(d['pillars'], list) else str(d['pillars'])
                        entry += f"**Pillars:** {pillars_str}\n"
                    
                    entry += f"\n**Decision:** {decision}\n"
                    
                    if rationale:
                        entry += f"\n**Rationale:** {rationale}\n"
                    
                    # Add context if available (rich format)
                    if d.get('context'):
                        entry += f"\n**Context:** {d['context']}\n"
                    
                    # Add validation needed
                    if d.get('validationNeeded'):
                        validation = d['validationNeeded']
                        if isinstance(validation, list):
                            entry += f"\n**Validation Needed:**\n"
                            for v in validation:
                                entry += f"- {v}\n"
                    
                    decision_parts.append(entry)
                
                decisions = "\n".join(decision_parts)

            # Format open questions
            open_questions = ""
            if gdd_data.get("openQuestions"):
                question_parts = []
                for q in gdd_data["openQuestions"]:
                    q_id = q.get('id', 'OQ-XXX')
                    question = q.get('question', 'Unknown')
                    priority = q.get('priority', 'medium')
                    
                    entry = f"### {q_id}: {question}\n"
                    entry += f"**Priority:** {priority}\n"
                    
                    # Add owner if available
                    if q.get('owner'):
                        entry += f"**Owner:** {q['owner']}\n"
                    
                    # Add tags if available
                    if q.get('tags'):
                        tags = q['tags'] if isinstance(q['tags'], list) else [q['tags']]
                        entry += f"**Tags:** {', '.join(tags)}\n"
                    
                    # Add blocker info if available
                    if q.get('blockerFor'):
                        blockers = q['blockerFor'] if isinstance(q['blockerFor'], list) else [q['blockerFor']]
                        entry += f"**Blocks:** {', '.join(blockers)}\n"
                    
                    question_parts.append(entry)
                
                open_questions = "\n".join(question_parts)

            # Format design pillars (handle both string list and object list)
            pillars = ""
            if gdd_data.get("designPillars"):
                pillar_parts = []
                for pillar in gdd_data["designPillars"]:
                    if isinstance(pillar, str):
                        # Minimal format: just strings
                        pillar_parts.append(f"- {pillar}")
                    elif isinstance(pillar, dict):
                        # Rich format: objects with description
                        name = pillar.get('name', 'Unknown')
                        desc = pillar.get('description', '')
                        pillar_parts.append(f"- **{name}**: {desc}")
                pillars = "\n".join(pillar_parts)

            # Format core mechanics (handle both string list and object list)
            mechanics = ""
            if gdd_data.get("coreMechanics"):
                mechanic_parts = []
                for mech in gdd_data["coreMechanics"]:
                    if isinstance(mech, str):
                        # Minimal format: just strings
                        mechanic_parts.append(f"- {mech}")
                    elif isinstance(mech, dict):
                        # Rich format: objects with description
                        name = mech.get('name', 'Unknown')
                        desc = mech.get('description', '')
                        mechanic_parts.append(f"- **{name}**: {desc}")
                mechanics = "\n".join(mechanic_parts)

            # Generate decision log
            decision_log = design_dir / "decision_log.md"
            decision_log_content = f"""# Design Decision Log

**Project:** {project_config.name}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Design Decisions

{decisions if decisions else "No design decisions documented."}

---

*This document tracks all design decisions made through Thermite design sessions.*
"""
            decision_log.write_text(decision_log_content, encoding='utf-8')
            print(f"✓ Generated decision log at {decision_log}")

            # Generate open questions document
            open_q_file = design_dir / "open_questions.md"
            open_q_content = f"""# Open Design Questions

**Project:** {project_config.name}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Open Questions

{open_questions if open_questions else "No open questions documented."}

---

*This document tracks unresolved design questions that need answers.*
"""
            open_q_file.write_text(open_q_content, encoding='utf-8')
            print(f"✓ Generated open questions at {open_q_file}")

            # Generate GDD summary
            gdd_file = design_dir / "gdd.md"
            gdd_content = f"""# Game Design Document Summary

**Project:** {project_config.name}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Design Pillars

{pillars if pillars else "No design pillars documented."}

---

## Core Mechanics

{mechanics if mechanics else "No core mechanics documented."}

---

## Thermite Session Details

**Session Type:** {gdd_data.get('thermiteSessionType', 'boardroom-retreat')}
**Participants:** {", ".join(gdd_data.get('participants', []))}

---

## Related Documents

- [Decision Log](decision_log.md) - All design decisions
- [Open Questions](open_questions.md) - Unresolved questions

**Additional Artifacts:**
Check docs/design/ for specialized artifacts:
- core_loop.md - Gameplay loop specification
- economy_model.md - Economy systems and balance
- map_templates.md - Map design and layouts
- gear_registry.md - Items with stats and counterplay
- visual_language.md - Visual and audio design
- tech_spec.md - Technical architecture
- mvd_checklist.md - Prototype readiness checklist

---

*This document is a summary of the full Game Design Document. See related documents for details.*
"""
            gdd_file.write_text(gdd_content, encoding='utf-8')
            print(f"✓ Generated GDD summary at {gdd_file}")

            return True
        except Exception as e:
            print(f"Error generating GDD summary: {e}", file=sys.stderr)
            return False

    def generate_prd(self, project_config: ProjectConfig, tech_stack: dict = None) -> bool:
        """Generate initial prd.json from project configuration.

        Args:
            project_config: Project configuration
            tech_stack: Technology stack configuration

        Returns:
            True if generation was successful
        """
        try:
            prd_content = self.renderer.render_prd_json(project_config, tech_stack)
            prd_file = self.project_root / "prd.json"
            prd_file.write_text(prd_content, encoding='utf-8')
            return True
        except Exception as e:
            print(f"Error generating PRD: {e}", file=sys.stderr)
            return False

    def setup_workflow_docs_directory(self, project_config: ProjectConfig) -> bool:
        """Setup workflow documentation directory and copy template.

        Note: Actual workflow generation happens via the wizard skill (shared-workflow-generation).
        This method ensures the directory exists and template is available.

        Args:
            project_config: Project configuration

        Returns:
            True if setup was successful
        """
        try:
            # Create workflows directory in the target project
            workflows_dir = self.project_root / "docs" / "workflows"
            workflows_dir.mkdir(parents=True, exist_ok=True)

            # Note: Template copying would require knowing ralph-orchestra root
            # This is handled by the copy_ralph_orchestra_files method

            return True
        except Exception as e:
            print(f"Warning: Could not setup workflow docs directory: {e}", file=sys.stderr)
            return False
