"""
PRD Starter Generator - README and CLAUDE.md Generation

ReadmeGenerator class - handles generation of README.md and CLAUDE.md files
with all formatting helper methods.
"""

import sys
from pathlib import Path

from constants import (
    TECH_STACK_PREREQUISITES,
    AGENT_DESCRIPTIONS
)
from model_types import ProjectConfig
from utils import resolve_tech_stack_commands


class ReadmeGenerator:
    """Generates README.md and CLAUDE.md project documentation files."""

    def __init__(self, project_root: Path):
        """Initialize the readme generator.

        Args:
            project_root: Root directory of the project
        """
        self.project_root = Path(project_root).resolve()

    def generate_readme(self, project_config: ProjectConfig, tech_stack: dict,
                        agents: dict, research_data: dict = None) -> bool:
        """Generate README.md with project specifications.

        Args:
            project_config: Project configuration
            tech_stack: Technology stack configuration
            agents: Agents configuration dict
            research_data: Optional research data from pm-research-specialist

        Returns:
            True if generation was successful
        """
        try:
            readme_path = self.project_root / "README.md"

            # Get tech prerequisites
            runtime = tech_stack.get("runtime", "node")
            prerequisites = TECH_STACK_PREREQUISITES.get(
                runtime,
                [f"- **{runtime.capitalize()}** installed"]
            )
            prerequisites_text = "\n".join(prerequisites)

            # Get resolved commands
            commands = resolve_tech_stack_commands(tech_stack, research_data)
            init_command = commands["init"].replace("{PROJECT_NAME}", project_config.name)
            dev_command = commands.get("dev", "npm run dev")

            # Format agents table
            agents_table = self._format_agents_for_readme(agents)

            # Get config filename based on runtime
            config_filename = self._get_config_filename(tech_stack)

            # Generate documentation links
            doc_links = self._generate_doc_links(project_config)

            # Build content
            content = f"""# {project_config.name}

{project_config.description}

## Overview

**Category:** {project_config.project_type.value}
**Tech Stack:** {tech_stack.get('description', tech_stack.get('runtime', 'node'))}
**Team Size:** {tech_stack.get('teamSize', 'Solo')}

## Quick Start

### Prerequisites

{prerequisites_text}

### Installation

```bash
{init_command}
```

### Development

```bash
{dev_command}
```

## Project Structure

```
{self.project_root.name}/
├── src/           # Source code
├── tests/         # Test files
├── docs/          # Documentation
├── .claude/        # Claude Code configuration
├── prd.json       # Project requirements
└── {config_filename}  # Project config
```

## Development

### Available Agents

This project uses Ralph Orchestra with the following agents:

{agents_table}

### Ralph Commands

```bash
# Start event-driven mode (recommended)
.\\.claude\\scripts\\ralph-event-session.ps1

# Start sequential mode (token-efficient)
.\\.claude\\scripts\\ralph-single-session.ps1

# Start HITL mode (learning)
/ralph-hitl
```

## Documentation

{doc_links}

## License

MIT

---
*Generated by Ralph Orchestra PRD Starter*
"""

            readme_path.write_text(content, encoding='utf-8')
            print(f"✓ Generated README.md at {readme_path}")
            return True
        except Exception as e:
            print(f"Error generating README.md: {e}", file=sys.stderr)
            return False

    def generate_claude_md(self, project_config: ProjectConfig, tech_stack: dict,
                          agents: dict, quality_standards: dict,
                          research_data: dict = None) -> bool:
        """Generate CLAUDE.md with project-specific Claude instructions.

        Args:
            project_config: Project configuration
            tech_stack: Technology stack configuration
            agents: Agents configuration dict
            quality_standards: Quality standards from Phase 7
            research_data: Optional research data from pm-research-specialist

        Returns:
            True if generation was successful
        """
        try:
            claude_md_path = self.project_root / "CLAUDE.md"

            # Get resolved commands for feedback loops
            commands = resolve_tech_stack_commands(tech_stack, research_data)

            # Format tech stack details
            tech_stack_details = self._get_tech_stack_details(tech_stack)

            # Format quality standards
            quality_text = self._format_quality_standards(quality_standards)

            # Format feedback loops
            feedback_loops = self._format_feedback_loops_for_claude(commands)

            # Format agent assignments
            agent_assignments = self._format_agent_assignments_for_claude(agents)

            # Get context notes
            context_notes = self._get_context_notes(project_config, tech_stack)

            # Get important patterns
            important_patterns = self._get_important_patterns(tech_stack)

            # Get common commands
            common_commands = self._get_common_commands(commands)

            # Get project-specific instructions
            project_instructions = self._get_project_instructions(project_config)

            # Build key files section
            key_files = self._generate_key_files_section(project_config)

            content = f"""# {project_config.name} - Claude Documentation

## Overview

{project_config.description}

## Tech Stack

**Primary:** {tech_stack.get('description', tech_stack.get('runtime', 'node'))}

{tech_stack_details}

## Project Structure

| Directory | Purpose |
|-----------|---------|
| `src/` | Main source code |
| `tests/` | Test files |
| `docs/` | Project documentation |
| `.claude/` | Claude Code configuration |

## Development Guidelines

### Code Standards

{quality_text}

### Feedback Loops

The following feedback loops are configured:

{feedback_loops}

## Agent Assignments

| Agent | Responsibilities |
|-------|-----------------|
{agent_assignments}

{key_files}

## Context Notes

{context_notes}

### Important Patterns

{important_patterns}

### Common Commands

{common_commands}

## Project-Specific Instructions

{project_instructions}

---
*Generated by Ralph Orchestra PRD Starter*
"""

            claude_md_path.write_text(content, encoding='utf-8')
            print(f"✓ Generated CLAUDE.md at {claude_md_path}")
            return True
        except Exception as e:
            print(f"Error generating CLAUDE.md: {e}", file=sys.stderr)
            return False

    # ========================================================================
    # Helper Methods for README/CLAUDE.md Generation
    # ========================================================================

    def _format_agents_for_readme(self, agents: dict) -> str:
        """Format agents as markdown table for README.

        Args:
            agents: Agents configuration dict

        Returns:
            Formatted markdown table string
        """
        rows = []
        for agent_name, agent_data in agents.items():
            if agent_data.get("enabled", False):
                display_name = agent_data.get("display_name", agent_name.title())
                role = agent_data.get("role", agent_name)
                desc = AGENT_DESCRIPTIONS.get(role, f"{display_name} agent")
                rows.append(f"| **{display_name}** | {desc} |")
        return "\n".join(rows) if rows else "| No agents configured | |"

    def _format_agent_assignments_for_claude(self, agents: dict) -> str:
        """Format agent assignments for CLAUDE.md.

        Args:
            agents: Agents configuration dict

        Returns:
            Formatted markdown table string
        """
        rows = []
        for agent_name, agent_data in agents.items():
            if agent_data.get("enabled", False):
                display_name = agent_data.get("display_name", agent_name.title())
                role = agent_data.get("role", agent_name)
                responsibilities = agent_data.get("primary_responsibility",
                    AGENT_DESCRIPTIONS.get(role, f"{display_name} responsibilities"))
                rows.append(f"| {display_name} | {responsibilities} |")
        return "\n".join(rows) if rows else "| No agents configured | |"

    def _format_feedback_loops_for_claude(self, commands: dict) -> str:
        """Format feedback loops for CLAUDE.md.

        Args:
            commands: Resolved commands dict

        Returns:
            Formatted feedback loops string
        """
        loops = []
        if commands.get("type_check"):
            loops.append(f"- **Type Check:** `{commands['type_check']}`")
        if commands.get("test"):
            loops.append(f"- **Test:** `{commands['test']}`")
        if commands.get("build"):
            loops.append(f"- **Build:** `{commands['build']}`")
        if commands.get("lint"):
            loops.append(f"- **Lint:** `{commands['lint']}`")
        return "\n".join(loops) if loops else "- No feedback loops configured"

    def _get_tech_stack_details(self, tech_stack: dict) -> str:
        """Get detailed tech stack information.

        Args:
            tech_stack: Technology stack configuration

        Returns:
            Formatted tech stack details
        """
        runtime = tech_stack.get("runtime", "node")
        framework = tech_stack.get("framework", "")
        details = [f"- **Runtime:** {runtime}"]
        if framework:
            details.append(f"- **Framework:** {framework}")
        return "\n".join(details)

    def _format_quality_standards(self, quality_standards: dict) -> str:
        """Format quality standards for CLAUDE.md.

        Args:
            quality_standards: Quality standards dict

        Returns:
            Formatted quality standards string
        """
        if not quality_standards:
            return "- Standard production quality"

        standards = []
        if quality_standards.get("typescriptStrictness") == "strict":
            standards.append("- **TypeScript:** Strict mode, no `any` types without justification")
        if quality_standards.get("testCoverageTarget"):
            standards.append(f"- **Test Coverage:** {quality_standards['testCoverageTarget']}% target")
        if quality_standards.get("lintRules"):
            standards.append(f"- **Linting:** {quality_standards['lintRules']}")
        if quality_standards.get("commitConvention"):
            standards.append(f"- **Commits:** {quality_standards['commitConvention']}")

        return "\n".join(standards) if standards else "- Standard production quality"

    def _get_context_notes(self, project_config: ProjectConfig, tech_stack: dict) -> str:
        """Generate context notes for Claude.

        Args:
            project_config: Project configuration
            tech_stack: Technology stack configuration

        Returns:
            Context notes string
        """
        notes = [
            f"This is a **{project_config.project_type.value}** project named **{project_config.name}**.",
            f"Tech stack: {tech_stack.get('description', tech_stack.get('runtime', 'node'))}",
            f"Team size: {tech_stack.get('teamSize', 'Solo')}"
        ]
        return "\n\n".join(notes)

    def _get_important_patterns(self, tech_stack: dict) -> str:
        """Get important coding patterns for the tech stack.

        Args:
            tech_stack: Technology stack configuration

        Returns:
            Important patterns string
        """
        runtime = tech_stack.get("runtime", "node")

        patterns = {
            "node": "- Use functional components where possible\n- Prefer composition over inheritance\n- Use async/await for asynchronous operations",
            "python": "- Follow PEP 8 style guidelines\n- Use type hints for all functions\n- Prefer dataclasses over plain classes",
            "rust": "- Use Result<T, E> for error handling\n- Prefer iterators over collections\n- Leverage borrow checker",
            "go": "- Prefer interfaces over concrete types\n- Use goroutines for concurrency\n- Handle errors explicitly",
            "java": "- Use dependency injection\n- Follow Java naming conventions\n- Prefer immutable objects",
            "dotnet": "- Use async/await for I/O\n- Prefer dependency injection\n- Follow C# naming conventions"
        }

        return patterns.get(runtime, "- Follow language best practices")

    def _get_common_commands(self, commands: dict) -> str:
        """Get common development commands.

        Args:
            commands: Resolved commands dict

        Returns:
            Common commands string
        """
        cmds = []
        if commands.get("install"):
            cmds.append(f"- Install: `{commands['install']}`")
        if commands.get("test"):
            cmds.append(f"- Test: `{commands['test']}`")
        if commands.get("build"):
            cmds.append(f"- Build: `{commands['build']}`")
        if commands.get("dev"):
            cmds.append(f"- Dev: `{commands['dev']}`")
        return "\n".join(cmds) if cmds else "- See package manager documentation"

    def _get_project_instructions(self, project_config: ProjectConfig) -> str:
        """Get project-specific instructions for Claude.

        Args:
            project_config: Project configuration

        Returns:
            Project-specific instructions string
        """
        category = project_config.project_type.value
        instructions = {
            "game": "This is a **game project**. Prioritize gameplay mechanics, visual feedback, and player experience. Use the Game Design Document (docs/design/gdd.md) when implementing features.",
            "web": "This is a **web application**. Prioritize responsive design, accessibility (WCAG 2.1), and performance. Follow modern web best practices.",
            "mobile": "This is a **mobile app**. Prioritize mobile-first design, touch interactions, and platform-specific guidelines (iOS/Android).",
            "backend": "This is a **backend API**. Prioritize security (input validation, authentication), data validation, and API documentation. Follow REST/GraphQL best practices.",
            "data": "This is a **data/ML project**. Prioritize data quality, reproducibility, and documentation. Follow data science best practices.",
            "devops": "This is a **DevOps** project. Prioritize infrastructure as code, security, and monitoring. Follow GitOps/CI/CD best practices.",
        }
        return instructions.get(category, "Follow standard best practices for this project type.")

    def _get_config_filename(self, tech_stack: dict) -> str:
        """Get config filename based on tech stack.

        Args:
            tech_stack: Technology stack configuration

        Returns:
            Config filename
        """
        runtime = tech_stack.get("runtime", "node")
        config_files = {
            "node": "package.json",
            "python": "requirements.txt",
            "rust": "Cargo.toml",
            "go": "go.mod",
            "java": "pom.xml",
            "dotnet": "PROJECT.csproj"
        }
        return config_files.get(runtime, "config")

    def _generate_doc_links(self, project_config: ProjectConfig) -> str:
        """Generate documentation links section.

        Args:
            project_config: Project configuration

        Returns:
            Documentation links string
        """
        links = []

        # Check if PRD exists
        prd_path = self.project_root / "prd.json"
        if prd_path.exists():
            links.append("- **[prd.json](prd.json)** - Project requirements and tasks")

        # Check if GDD exists (game projects)
        gdd_path = self.project_root / "docs" / "design" / "gdd.md"
        if gdd_path.exists():
            links.append("- **[Game Design Document](docs/design/gdd.md)** - Game design specifications")

        # Check if research summary exists
        research_path = self.project_root / "docs" / "research-summary.md"
        if research_path.exists():
            links.append("- **[Research Summary](docs/research-summary.md)** - Research findings")

        # Check if workflows exist
        workflows_readme = self.project_root / "docs" / "workflows" / "README.md"
        if workflows_readme.exists():
            links.append("- **[Workflow Documentation](docs/workflows/)** - Development workflows")

        return "\n".join(links) if links else "- See docs/ directory for project documentation"

    def _generate_key_files_section(self, project_config: ProjectConfig) -> str:
        """Generate key files section for CLAUDE.md.

        Args:
            project_config: Project configuration

        Returns:
            Key files section string
        """
        files = []

        # PRD always referenced
        files.append("- **[`prd.json`](prd.json)** - Project requirements and tasks")

        # GDD for game projects
        gdd_path = self.project_root / "docs" / "design" / "gdd.md"
        if gdd_path.exists():
            files.append("- **[`docs/design/gdd.md`](docs/design/gdd.md)** - Game Design Document")
            files.append("- **[`docs/design/decision_log.md`](docs/design/decision_log.md)** - Design decisions")
            files.append("- **[`docs/design/open_questions.md`](docs/design/open_questions.md)** - Open questions")

        # Research summary if exists
        research_path = self.project_root / "docs" / "research-summary.md"
        if research_path.exists():
            files.append("- **[`docs/research-summary.md`](docs/research-summary.md)** - Research findings")

        return "\n".join(files)
